exec-once = ~/.local/bin/run-if-exists.sh otd-daemon
exec-once = ~/.local/bin/run-if-exists.sh udiskie

################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=DP-2,1920x1080@165.00Hz,1920x0,1
monitor=DP-3,1920x1080@165.00Hz,0x0,1


##################
### WORKSPACES ###
##################

# Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
# "Smart gaps" / "No gaps when only"
# uncomment all if you wish to use that.
# workspace = w[tv1], gapsout:0, gapsin:0
# workspace = f[1], gapsout:0, gapsin:0
# windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
# windowrule = rounding 0, floating:0, onworkspace:w[tv1]
# windowrule = bordersize 0, floating:0, onworkspace:f[1]
# windowrule = rounding 0, floating:0, onworkspace:f[1]
workspace=1,  monitor:DP-3
workspace=3,  monitor:DP-3
workspace=5,  monitor:DP-3
workspace=7,  monitor:DP-3
workspace=9,  monitor:DP-3
workspace=2,  monitor:DP-2
workspace=4,  monitor:DP-2
workspace=6,  monitor:DP-2
workspace=8,  monitor:DP-2
workspace=10, monitor:DP-2

# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name   = wacom-intuos-s-pen
    output = DP-2
}

# Reference https://wiki.hypr.land/hyprland-wiki/pages/Configuring/Window-Rules/#window-rules-v2
windowrulev2 = float, class:^(OpenTabletDriver.UX)$
windowrulev2 = center, class:^(OpenTabletDriver.UX)$
