require("~/.config/hypr/base-config.lua")
require("~/.config/hypr/desktop-config.lua")
-- require("~/.config/hypr/laptop-config.lua")
require("~/.config/hypr/plugins.lua")
require("~/.config/hypr/binds.lua")
require("~/.config/hypr/window-rules.lua")
require("~/.config/hypr/auto-start.lua")
require("~/.config/hypr/env.lua")
require("~/.config/hypr/animations.lua")
require("~/.config/hypr/decorations.lua")
