source = ~/.config/hypr/base-config.conf
source = ~/.config/hypr/desktop-config.conf
# source = ~/.config/hypr/laptop-config.conf
source = ~/.config/hypr/plugins.conf
source = ~/.config/hypr/binds.conf
