exec-once = hyprctl plugin load ~/.config/hypr/plugins/Hyprspace/Hyprspace.so

# Workspace view- https://github.com/KZDKM/Hyprspace
$mainMod = SUPER
bind = $mainMod SHIFT, e, exec, hyprctl dispatch overview:toggle all

plugin {

    # Workspace view- https://github.com/KZDKM/Hyprspace
    overview {
        enabled = true
        autoDrag = true
        centerAligned = true
        onBottom = true
        drawActiveWorkspace = true
        exitOnClick = true
        switchOnDrop = false
        # adaptiveHeight = true
        # exitOnSwitch = true
        dragAlpha = 0.8
        disableGestures = 1

        workspaceMargin = 40
        panelHeight = 250
        workspaceActiveBorder = rgb(5c64f1)
        panelBorderWidth = 2
        panelBorderColor = rgb(5c64f1)

        showNewWorkspace = false
        showEmptyWorkspace = true
        affectStrut = false
        disableBlur = false
    }
}

