# Reference https://wiki.hypr.land/Configuring/Window-Rules/
windowrule {
    name = bitwarden-extension-popup
    match:title = .*Bitwarden.*
    float = on
    center = on
    stay_focused = on
}

windowrule {
    name = custom-popup-yad
    match:class = ^(yad)$
    float = on
    center = on
    stay_focused = on
}

windowrule {
    name = blueman-manager-popup
    match:class = ^(blueman-manager)$
    float = on
    center = on
}

windowrule {
    name = network-manager-connection-editor
    match:class = ^(nm-connection-editor)$
    float = on
    stay_focused = on
    move = (cursor_x-(window_w*0.5)) (cursor_y-(window_h*0.5))
}

windowrule {
    name = clipse-clipboard-manager
    match:class = ^(clipse-gui)$
    float = on
    stay_focused = on
    size = 622 652
    # move = cursor_x cursor_y
    center = on
}

windowrule {
    name = pavucontrol
    match:class = ^(pavucontrol)$
    float = on
    stay_focused = on
    size = 422 652
}

windowrule {
    # Make lxqt-policykit-agent dialogs float nicely
    name = lxqt-policykit-agent
    match:class = ^(lxqt-policykit-agent)$
    float = on
    center = on
    size = 600 0
    stay_focused = on
}

windowrule {
    name = thunar-rename
    match:class = ^(thunar)$
    match:title = ^(Rename .*)$
    float = on
    center = on
    stay_focused = on
}

windowrule {
    name = open-tablet-driver-ux
    match:class = ^(OpenTabletDriver.UX)$
    float = on
    center = on
}

layerrule {
    name = swaync-control-center
    match:class = ^(swaync-control-center)$
    blur = on
    ignore_alpha = 0.5
}

layerrule {
    name = swaync-notification-window
    match:class = ^(swaync-notification-window)$
    blur = on
    ignore_alpha = 0.5
}

windowrule {
    name = zed-settings
    match:class = ^(dev.zed.Zed)$
    match:title = ^(Zed — Settings)$
    float = on
    center = on
    stay_focused = on
    size = 1600 1000
}

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}


windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}
