# xdg-desktop-portal-hyprland config
# reference- https://wiki.hypr.land/Hypr-Ecosystem/xdg-desktop-portal-hyprland/#category-screencopy
screencopy {
    # sometimes solves the multiple popups issue
    # https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/11
    allow_token_by_default = true
}
